var input=prompt("Enter postitve integer number (i.e 3.142, 5.99999, 5561.2564)")
document.write("Number: "+input)
document.write("<br>round off value: "+Math.round(input))
document.write("<br>floor value: "+Math.floor(input))
document.write("<br>ceil value: "+Math.ceil(input))